[project]
name = "tooling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bibtexparser>=1.4.4",
    "pymupdf>=1.28.2",
    "rdflib>=7.6.0",
    "requests>=2.34.2",
    "tqdm>=4.70.0",
    "typer>=0.27.1",
]


[project.scripts]
tex-typst-helper = "tex_typst_helpers.cli:main"
texty-tool = "tex_typst_helpers.cli:main"
